# Generated by Django 5.0.3 on 2024-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customer_password_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
