# Generated by Django 5.0.3 on 2024-06-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_restaurant_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurantName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
