# Generated by Django 5.0.3 on 2024-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_menu_restaurantname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Image_url',
            field=models.URLField(default='https://placehold.co/200x250'),
        ),
    ]
