# Generated by Django 5.0.3 on 2024-06-05 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=8, unique=True)),
                ('restaurantName', models.CharField(default='', max_length=50)),
                ('Image_url', models.URLField(default='https://placehold.co/200x250')),
                ('name', models.CharField(max_length=100)),
                ('count', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sumTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
