# Generated by Django 5.0.3 on 2024-06-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='booking_date_time',
            field=models.DateField(),
        ),
    ]
