# Generated by Django 5.0.3 on 2024-06-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_orders_booking_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='booking_date_time',
            new_name='booking_date',
        ),
    ]
